"""initial migration

Revision ID: 086d7b3c8e96
Revises: 
Create Date: 2025-11-12 13:50:41.877346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '086d7b3c8e96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_events_raw',
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('has_detection', sa.Boolean(), sa.Computed("COALESCE(jsonb_array_length(event_data->'detectedObjects'), 0) > 0", persisted=True), nullable=True),
    sa.Column('detection_count', sa.SmallInteger(), sa.Computed("COALESCE(jsonb_array_length(event_data->'detectedObjects'), 0)", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('camera_id', 'event_time', name=op.f('pk_camera_events_raw'))
    )
    op.create_index('idx_camera_events_detection', 'camera_events_raw', ['camera_id', sa.text('event_time DESC')], unique=False, postgresql_where=sa.text('has_detection = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_camera_events_detection', table_name='camera_events_raw', postgresql_where=sa.text('has_detection = true'))
    op.drop_table('camera_events_raw')
    # ### end Alembic commands ###